name: master

on:
  push:
    branches: [master]

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
      - uses: nuget/setup-nuget@v2
      - uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64

      - name: NuGet restore
        run: nuget restore Fb2Kindle.sln

      - name: Build
        run: msbuild Fb2Kindle.sln -p:Configuration=Release -m

      # - name: Publish build
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: Fb2Kindle
      #     path: |
      #       Fb2Kindle/bin/Obfuscator_Output